-- Seed data: 20 historical sanctions episodes from history/api/sanctions-database.json
-- NOTE: embedding column left NULL; populate via scripts/generate-embeddings.ts

INSERT INTO episodes (
  episode_id, name, start_date, end_date, initiators, target,
  target_gdp_pct_world, sector, goals, multilateral, un_backed,
  enforcement_intensity, measures, trigger_event, workarounds,
  target_economy, outcome, objective_achieved, outcomes_6mo, outcomes_12mo,
  success_score, time_to_impact_months, time_to_resolution_months,
  key_turning_points, resolution, lessons, tags, key_sources, wikipedia_url, narrative
) VALUES

-- 1. Iran Nuclear 2012
(
  'IRN2012_NUCLEAR',
  'Iran Nuclear Sanctions (P5+1 Comprehensive Regime)',
  '2012-01-01', '2015-07-14',
  ARRAY['US','EU','UN'],
  'Iran', 0.55, 'energy_finance',
  ARRAY['Compel Iran to negotiate verifiable limits on its nuclear program and accept enhanced IAEA oversight'],
  true, true, 'critical',
  ARRAY['SWIFT disconnection of Iranian banks (March 2012)','EU oil import ban','US secondary sanctions on third-country banks dealing with Iran','Asset freezes on Central Bank of Iran','Ban on Iranian shipping and insurance','Gold and precious metals trade ban','Restrictions on petrochemical exports'],
  'Iran''s continued uranium enrichment beyond IAEA-agreed limits and refusal to allow inspections, combined with intelligence assessments of possible weapons-development activities',
  ARRAY['Ghost fleet of tankers with disabled AIS transponders and frequent flag-hopping across registry jurisdictions','Hawala-style shadow banking using Dubai-based front companies to move hundreds of millions in cash outside SWIFT','Oil sold at deep discounts through Chinese intermediaries and routed through Malaysian and Emirati shell companies','Misrepresented cargo manifests and ship-to-ship transfers in open waters to obscure oil origin','Barter arrangements (oil-for-goods) to avoid dollar-denominated transactions'],
  '{"gdp_change_pct": -8.5, "oil_export_change_pct": -55, "inflation_pct": 45.1, "currency_devaluation_pct": 56, "alternative_partners": ["China","India","Turkey","South Korea"]}',
  'negotiated_relief', 'partial',
  '{"scenarios": [{"label": "partial_compliance", "probability": 0.35}, {"label": "escalation", "probability": 0.20}, {"label": "status_quo", "probability": 0.30}, {"label": "negotiated_relief", "probability": 0.15}], "gdp_impact_pct": -5.2, "currency_devaluation_pct": 40}',
  '{"scenarios": [{"label": "partial_compliance", "probability": 0.40}, {"label": "escalation", "probability": 0.15}, {"label": "status_quo", "probability": 0.20}, {"label": "negotiated_relief", "probability": 0.25}], "gdp_impact_pct": -8.5, "oil_export_drop_pct": 55}',
  0.62, 6, 42,
  ARRAY['March 2012: SWIFT disconnection triggers rial collapse and 40%+ inflation, demonstrating unprecedented financial leverage','November 2013: Interim Geneva agreement (Joint Plan of Action) provides partial sanctions relief in exchange for uranium enrichment freeze, proving Iran willing to negotiate under pressure','July 2015: JCPOA signed — Iran agrees to cap enrichment at 3.67%, reduce centrifuges by two-thirds, and accept IAEA cameras in exchange for sanctions removal'],
  'JCPOA signed July 14, 2015, with sanctions lifted on Implementation Day (January 16, 2016) after IAEA verified Iranian compliance. Iran rapidly restored oil exports to over 2 million b/d. US withdrew from JCPOA in May 2018, reimposing maximum-pressure sanctions.',
  ARRAY['SWIFT exclusion is the most powerful single financial weapon available to Western sanctioners, capable of causing near-immediate currency collapse in an oil-dependent economy','Secondary sanctions (threatening third-country banks) are essential for effectiveness — without them, China and India continued purchasing Iranian oil at discount, partially cushioning the blow','Sanctions succeeded in bringing Iran to the table but not in eliminating its nuclear capabilities; they produced a negotiated compromise rather than capitulation, underscoring the gap between pressure and compliance'],
  ARRAY['nuclear','SWIFT','oil','JCPOA','secondary-sanctions','Middle East'],
  ARRAY['https://en.wikipedia.org/wiki/International_sanctions_against_Iran','OFAC Iran sanctions 2012','IAEA Board of Governors reports 2012-2015'],
  'https://en.wikipedia.org/wiki/International_sanctions_against_Iran',
  'The P5+1 imposed the most comprehensive financial sanctions ever applied to Iran, culminating in SWIFT disconnection in March 2012. GDP contracted 8.5%, oil exports fell 55%, and inflation exceeded 45%. Iran negotiated the JCPOA in July 2015 — the most successful sanctions case of the modern era, though the deal later collapsed after US withdrawal in 2018. Key lesson: SWIFT exclusion plus secondary sanctions on third-country banks is the most powerful financial toolkit available.'
),

-- 2. Russia Crimea 2014
(
  'RUS2014_CRIMEA',
  'Russia Post-Crimea Annexation Sanctions',
  '2014-03-17', NULL,
  ARRAY['US','EU','Canada','Australia','Japan'],
  'Russia', 1.78, 'finance_energy',
  ARRAY['Compel Russia to reverse Crimea annexation, withdraw support from Donbas separatists, and comply with the Minsk ceasefire agreements'],
  true, false, 'high',
  ARRAY['Asset freezes and travel bans on named officials and oligarchs','Sectoral sanctions on Russian energy, defense, and finance sectors','Restrictions on Western banks lending to major Russian state banks (Sberbank, VTB, Gazprombank)','Ban on export of dual-use technology for oil exploration','Prohibition on new investment in Crimea','Arms embargo on Russia'],
  'Russia''s annexation of Crimea from Ukraine in March 2014, followed by covert military support for separatists in eastern Ukraine (Donbas)',
  ARRAY['Pivot to Chinese banks and yuan-denominated trade to bypass Western financial system','Re-routing goods through Belarus and Kazakhstan under the Eurasian Economic Union framework','Use of sanctioned oligarchs'' assets held through complex offshore ownership structures in Cyprus, British Virgin Islands, and UAE','Continued oil and gas sales to Europe through existing long-term contracts (which were explicitly exempted from sanctions)'],
  '{"gdp_change_pct": -3.7, "oil_export_change_pct": null, "inflation_pct": 11.4, "currency_devaluation_pct": 58.2, "alternative_partners": ["China","India","Belarus","Kazakhstan"]}',
  'stalemate', 'no',
  '{"scenarios": [{"label": "partial_compliance", "probability": 0.12}, {"label": "escalation", "probability": 0.45}, {"label": "status_quo", "probability": 0.35}, {"label": "negotiated_freeze", "probability": 0.08}], "gdp_impact_pct": -2.1, "ruble_depreciation_pct": 46}',
  '{"scenarios": [{"label": "partial_compliance", "probability": 0.08}, {"label": "escalation", "probability": 0.50}, {"label": "status_quo", "probability": 0.34}, {"label": "negotiated_freeze", "probability": 0.08}], "gdp_impact_pct": -3.7, "export_revenue_decline_pct": 12}',
  0.18, 8, NULL,
  ARRAY['December 2014: Ruble collapses 58% against the dollar, forcing Russian central bank to raise rates to 17% — the most severe immediate financial shock','February 2015: Minsk II agreement signed but never implemented; sanctions maintained despite nominal compliance process','2016–2019: Russian economy stabilizes and grows modestly as oil prices recover, demonstrating sanctions limited long-term coercive leverage when not paired with oil embargo'],
  'Sanctions remain in place as of 2026. Russia never reversed Crimea annexation. The regime was later superseded by far broader 2022 post-Ukraine invasion sanctions.',
  ARRAY['Sectoral sanctions without full energy embargo provide insufficient coercive leverage against a major oil exporter — Russia''s hydrocarbon revenues continued funding the state even as finance and technology sectors were squeezed','The 2014 sanctions were significantly diluted by European reluctance to cut energy imports, demonstrating that coalition cohesion is the critical variable in multilateral sanctions effectiveness','Ruble depreciation and capital flight imposed real economic costs but did not alter Russian foreign policy; economic pain and policy capitulation are not reliably linked in authoritarian petrostate contexts'],
  ARRAY['Russia','Crimea','Ukraine','energy','financial','sectoral'],
  ARRAY['https://en.wikipedia.org/wiki/International_sanctions_during_the_Russo-Ukrainian_war','EU Council Regulation 269/2014','Peterson Institute for International Economics 2015'],
  'https://en.wikipedia.org/wiki/International_sanctions_during_the_Russo-Ukrainian_war',
  'Western allies imposed sectoral sanctions on Russian finance, energy, and defense sectors following the annexation of Crimea in March 2014. The ruble collapsed 46% and capital outflows reached $151 billion in 2014, but Russia adapted rapidly through import substitution and closer ties with China. Territorial objectives were not reversed. Canonical case of high-intensity multilateral sanctions failing to achieve primary political goals against a major economy with diversified external relationships.'
),

-- 3. Russia Ukraine 2022
(
  'RUS2022_UKRAINE',
  'Russia Post-Ukraine Invasion Comprehensive Sanctions',
  '2022-02-24', NULL,
  ARRAY['US','EU','UK','Canada','Japan','Australia','South Korea','Switzerland'],
  'Russia', 1.72, 'comprehensive',
  ARRAY['Impose maximum economic cost to degrade Russia''s war-fighting capacity, force withdrawal from Ukraine, and deter further aggression'],
  true, false, 'critical',
  ARRAY['Removal of major Russian banks from SWIFT (including Sberbank, VTB)','Freeze on ~$300 billion in Russian central bank foreign reserves held in Western jurisdictions','G7/EU oil price cap of $60/barrel on Russian crude (December 2022)','Full ban on Russian oil imports by EU and US','Export controls on semiconductors, advanced technology, and dual-use goods','Asset freezes and travel bans on over 1,500 individuals and entities','Ban on Russian aircraft in Western airspace','Prohibition on gold imports from Russia'],
  'Russia''s full-scale invasion of Ukraine on February 24, 2022',
  ARRAY['Shadow fleet of 400+ tankers with obscured ownership transporting 65-70% of Russia''s seaborne oil exports outside price-cap monitoring','Parallel import schemes through Turkey, Kazakhstan, UAE, and Armenia re-exporting sanctioned Western goods to Russia','Redirection of oil exports to India and China at deep discounts (~$20-30/barrel below Brent)','Use of Russia''s SPFS (domestic SWIFT alternative) linked to Chinese CIPS for financial transactions','AIS transponder manipulation and ship-to-ship transfers in Turkish straits and Indian Ocean to disguise cargo origin'],
  '{"gdp_change_pct": -2.1, "oil_export_change_pct": -25, "inflation_pct": 13.7, "currency_devaluation_pct": 40, "alternative_partners": ["China","India","Turkey","UAE","Kazakhstan"]}',
  'ongoing', 'no',
  '{"scenarios": [{"label": "partial_compliance", "probability": 0.05}, {"label": "escalation", "probability": 0.55}, {"label": "status_quo", "probability": 0.30}, {"label": "negotiated_ceasefire", "probability": 0.10}], "gdp_impact_pct": -2.1, "reserve_freeze_bn_usd": 300}',
  '{"scenarios": [{"label": "partial_compliance", "probability": 0.08}, {"label": "escalation", "probability": 0.45}, {"label": "status_quo", "probability": 0.35}, {"label": "negotiated_ceasefire", "probability": 0.12}], "gdp_impact_pct": -2.1, "oil_revenue_loss_bn_usd": 20}',
  0.15, 3, NULL,
  ARRAY['February–March 2022: Freezing of $300 billion in Russian central bank reserves represents the largest-ever sovereign asset seizure; ruble initially plunges 40% before recovering on capital controls','December 2022: G7 oil price cap implementation forces Russia to rapidly expand shadow fleet and redirect exports to Asia, costing an estimated $15-20 billion in annual revenue','2023–2025: Russia''s economy proves more resilient than forecast (growing 3.6% in 2023) due to war-driven fiscal stimulus, import substitution, and record revenues from Asian oil sales'],
  'Ongoing as of March 2026. Russia continues fighting in Ukraine. Oil revenues recovering via shadow fleet and Asian buyers. Frozen reserves remain subject to G7 debate over seizure for Ukraine reconstruction.',
  ARRAY['Freezing sovereign reserves is a powerful escalation tool but not an immediate coercive lever — Russia adapted through capital controls and redirected trade before reserves mattered operationally','The shadow fleet ecosystem (pioneered by Iran, replicated by Russia and Venezuela) represents a structural failure in the oil price cap mechanism; enforcing the cap requires sanctioning Indian and Chinese refiners, a step Western governments have been unwilling to take','War-economy dynamics can substantially offset sanctions costs — Russian military spending (40% of 2024 federal budget) provided Keynesian stimulus that partially substituted for lost private economic activity'],
  ARRAY['Russia','Ukraine','SWIFT','oil-price-cap','shadow-fleet','frozen-reserves','comprehensive'],
  ARRAY['https://en.wikipedia.org/wiki/International_sanctions_during_the_Russo-Ukrainian_war','OFAC Russia sanctions 2022','EU sanctions packages 2022-2024'],
  'https://en.wikipedia.org/wiki/International_sanctions_during_the_Russo-Ukrainian_war',
  'The broadest sanctions package in modern history, imposed following Russia''s full-scale invasion of Ukraine on February 24, 2022. Over $300 billion in central bank reserves frozen, SWIFT access removed for major banks, and an oil price cap implemented. Despite initial shock, Russia''s economy proved resilient through war-economy stimulus, shadow fleet oil exports, and Asian market redirection. GDP fell only 2.1% versus predictions of 10-15%. Ongoing as of 2026 with no resolution in sight.'
),

-- 4. North Korea Nuclear
(
  'PRK2006_NUCLEAR',
  'North Korea Nuclear and Missile Sanctions',
  '2006-10-09', NULL,
  ARRAY['UN','US','EU','South Korea','Japan'],
  'North Korea', 0.02, 'defense_nuclear',
  ARRAY['Achieve complete, verifiable, and irreversible denuclearization (CVID) of the Korean Peninsula'],
  true, true, 'critical',
  ARRAY['Ban on exports of coal, iron, lead, seafood, textiles (UN Resolution 2371, 2375, 2397)','Cap on North Korean oil imports (500,000 barrels/year refined petroleum; 4 million barrels crude)','Ban on North Korean laborers working abroad','Asset freezes on Workers'' Party, Reconnaissance General Bureau, and named officials','Arms embargo (total, both import and export)','Ban on luxury goods imports','Prohibition on joint ventures with North Korean entities'],
  'North Korea''s first nuclear test on October 9, 2006; subsequent tests in 2009, 2013, 2016 (twice), and 2017 triggered progressively tighter sanctions',
  ARRAY['Ship-to-ship transfers of coal and oil in international waters — UN Panel documented 3.7 million tons of coal exported via such transfers in January-August 2019 alone, worth ~$370 million','Over 300 North Korean-linked companies in China''s Liaoning province; extensive networks of Chinese nationals acting as front-company operators','Cyber heists — Lazarus Group stole an estimated $316 million from cryptocurrency exchanges in 2019-2020 alone; total cyber theft estimated at $3 billion+ since 2016','Diplomatic pouch smuggling of luxury goods, narcotics, and currency through overseas diplomatic missions','AIS spoofing and vessel identity fraud — ships assume identities of legitimate foreign-flagged vessels to enter ports'],
  '{"gdp_change_pct": -15.3, "oil_export_change_pct": null, "inflation_pct": null, "currency_devaluation_pct": null, "alternative_partners": ["China","Russia"]}',
  'evasion', 'no',
  '{"scenarios": [{"label": "compliance", "probability": 0.02}, {"label": "escalation", "probability": 0.60}, {"label": "status_quo", "probability": 0.35}, {"label": "negotiation", "probability": 0.03}], "gdp_impact_pct": -5.0}',
  '{"scenarios": [{"label": "compliance", "probability": 0.02}, {"label": "escalation", "probability": 0.65}, {"label": "status_quo", "probability": 0.30}, {"label": "negotiation", "probability": 0.03}], "gdp_impact_pct": -15.3}',
  0.04, 18, NULL,
  ARRAY['2017: UN Resolutions 2371 and 2375 ban coal, iron, and seafood exports worth ~$3 billion/year — the tightest sanctions in DPRK history, backed by Chinese support after the sixth nuclear test','2019: Trump-Kim Singapore and Hanoi summits collapse without agreement; North Korea resumes missile testing and ramps up cyber operations to compensate for sanctions-driven revenue loss','2022: Russia and China veto further UN Security Council sanctions after Russia invades Ukraine; North Korea provides artillery shells to Russia, effectively breaking out of isolation'],
  'Ongoing. North Korea has conducted over 100 ballistic missile tests since 2022 and continues nuclear program development. Denuclearization objective has not been achieved. DPRK-Russia arms cooperation has materially weakened the sanctions coalition.',
  ARRAY['Sanctions that rely on Chinese enforcement against a Chinese-border state face an irreducible compliance problem: China''s strategic interest in preventing North Korean collapse reliably overrides its commitment to sanctions pressure','Cybercrime as a sanctions evasion tool is a qualitative innovation — unlike physical smuggling, it scales without geographic constraint and is extremely difficult to interdict, generating billions in hard currency annually','Prolonged maximum-pressure campaigns against nuclear-armed states can entrench rather than reverse proliferation by removing the regime''s incentive to bargain away its only existential deterrent'],
  ARRAY['nuclear','DPRK','Korea','cyber','arms-embargo','ship-to-ship','China-dependence'],
  ARRAY['https://en.wikipedia.org/wiki/International_sanctions_against_North_Korea','UN Panel of Experts Reports 2006-2023','US Treasury OFAC DPRK designations'],
  'https://en.wikipedia.org/wiki/International_sanctions_against_North_Korea',
  'The UN and US have imposed progressively tighter sanctions on North Korea since its first nuclear test in 2006. Despite GDP contracting 15.3%, DPRK has continued nuclear and missile development, developed cyber theft capabilities generating $3+ billion, and exploited Chinese non-enforcement. The Lazarus Group cyber operations represent a structural innovation that provides hard currency sanctions cannot intercept. The nuclear deterrent logic makes compliance less likely as sanctions intensify — the regime calculates it cannot give up its weapons program.'
),

-- 5. Cuba Embargo 1962
(
  'CUB1962_EMBARGO',
  'US Embargo Against Cuba',
  '1962-02-07', NULL,
  ARRAY['US'],
  'Cuba', 0.07, 'comprehensive',
  ARRAY['Initially: weaken the Castro regime to force its collapse or policy reversal. Post-Cold War: promote democracy and human rights in Cuba'],
  false, false, 'critical',
  ARRAY['Total ban on US exports to Cuba (except food and medicine after 2000)','Total ban on US imports from Cuba','Prohibition on US citizens traveling to Cuba and spending money there','Freeze on Cuban government assets in the US','Prohibition on foreign subsidiaries of US firms trading with Cuba (Helms-Burton Act, 1996)','Third-country shipping restrictions (ships calling in Cuban ports barred from US ports for 6 months)'],
  'Cuba''s nationalization of US-owned properties and its geopolitical alignment with the Soviet Union during the Cold War; formally established February 1962 by President Kennedy',
  ARRAY['Soviet Union provided subsidies averaging $4.3 billion/year (1986-1990), representing 21% of Cuban GNP — purchasing Cuban sugar at 6x world market price and selling oil below market price','Cuba re-exported below-market Soviet oil on world markets, generating hard currency equal to 40% of total revenues','European, Canadian, and Latin American trade and tourism provided substitute income streams outside US jurisdiction','Post-1990: Venezuela under Chávez supplied 100,000 barrels/day at preferential rates in exchange for Cuban doctors, partially replacing Soviet subsidies'],
  '{"gdp_change_pct": -33, "oil_export_change_pct": null, "inflation_pct": null, "currency_devaluation_pct": null, "alternative_partners": ["Soviet Union","Venezuela","China","Canada","European Union","Russia"]}',
  'evasion', 'no',
  '{"scenarios": [{"label": "compliance", "probability": 0.02}, {"label": "status_quo", "probability": 0.75}, {"label": "evasion_adaptation", "probability": 0.23}], "gdp_impact_pct": -5.0}',
  '{"scenarios": [{"label": "compliance", "probability": 0.02}, {"label": "status_quo", "probability": 0.70}, {"label": "evasion_adaptation", "probability": 0.28}], "gdp_impact_pct": -8.0}',
  0.03, 24, NULL,
  ARRAY['1991: Soviet collapse eliminates $4.3 billion/year in subsidies; Cuba''s GDP falls 33% by 1993 in the Special Period — the sanctions'' moment of maximum effectiveness as alternative patron disappeared','1996: Helms-Burton Act codifies embargo into law and extraterritorializes it; tightens but also entrenches the policy, removing presidential flexibility','2014-2016: Obama-era détente partially lifts travel and remittance restrictions; diplomatic relations restored — then reversed by Trump administration in 2017'],
  'Ongoing as of March 2026. The longest-running bilateral trade embargo in modern history. Cuba''s Communist government remains in power 64 years after the embargo was imposed. The UN General Assembly has voted to condemn the embargo annually since 1992, typically by margins of 185-2.',
  ARRAY['Unilateral sanctions against a small state are systematically circumvented when a major power has strategic interest in sponsoring the target — the effectiveness of sanctions is fundamentally a function of the target''s access to alternative patrons','The embargo''s endurance as a political institution despite its acknowledged policy failure illustrates how domestic interest groups can lock in ineffective sanctions regardless of strategic merit','Extraterritorial sanctions (Helms-Burton Title III) antagonize allied governments without meaningfully increasing target compliance, damaging coalition relationships needed for other foreign policy goals'],
  ARRAY['Cuba','Cold War','comprehensive','unilateral','Helms-Burton','longest-running'],
  ARRAY['https://en.wikipedia.org/wiki/United_States_embargo_against_Cuba','US OFAC Cuba sanctions','Helms-Burton Act 1996'],
  'https://en.wikipedia.org/wiki/United_States_embargo_against_Cuba',
  'The longest-running comprehensive trade embargo in modern history — imposed by the US on Cuba in February 1962 and still in effect as of 2026. Despite causing Cuba''s GDP to fall 33% during the Special Period (1990-1993) when Soviet subsidies collapsed, the regime survived by finding successive alternative patrons (Soviet Union, Venezuela, China). The canonical failure case for unilateral sanctions against a small state with access to major-power sponsorship.'
),

-- 6. Iraq 1990
(
  'IRQ1990_KUWAIT',
  'Iraq Comprehensive UN Sanctions',
  '1990-08-06', '2003-05-22',
  ARRAY['UN','US','UK'],
  'Iraq', 0.20, 'comprehensive',
  ARRAY['Initially: compel Iraqi withdrawal from Kuwait. Post-Gulf War: enforce UN resolutions on WMD disarmament, weapons inspections, and war reparations'],
  true, true, 'critical',
  ARRAY['Total trade embargo (UN Resolution 661, August 1990)','Oil export ban (except via Oil-for-Food Program from 1996)','Financial assets freeze','Arms embargo','Ban on civilian aviation','Restrictions on dual-use technology exports','No-fly zones enforced by US and UK air forces'],
  'Iraq''s invasion and annexation of Kuwait on August 2, 1990',
  ARRAY['Oil-for-Food Program corruption: Saddam''s regime extracted $1.7 billion in kickbacks from humanitarian goods suppliers and $10.9 billion from illegal oil smuggling','Illegal oil sales to Jordan (~8 million barrels/year), Turkey, Syria, and Egypt totaling ~$8 billion over the sanctions period','10% kickback demands on humanitarian contractors — nearly half of 4,500 participating companies paid bribes to win contracts','Petroleum sold via tanker trucks through Kurdish-controlled northern Iraq to Turkey','Iraqi officials bribed UN personnel overseeing the Oil-for-Food program'],
  '{"gdp_change_pct": -75, "oil_export_change_pct": -95, "inflation_pct": null, "currency_devaluation_pct": null, "alternative_partners": ["Jordan","Turkey","Syria","Egypt"]}',
  'partial_compliance', 'partial',
  '{"scenarios": [{"label": "compliance", "probability": 0.20}, {"label": "partial_compliance", "probability": 0.45}, {"label": "status_quo", "probability": 0.30}, {"label": "military_escalation", "probability": 0.05}], "gdp_impact_pct": -50}',
  '{"scenarios": [{"label": "compliance", "probability": 0.15}, {"label": "partial_compliance", "probability": 0.40}, {"label": "status_quo", "probability": 0.30}, {"label": "military_escalation", "probability": 0.15}], "gdp_impact_pct": -75}',
  0.45, 1, 152,
  ARRAY['August 1991: Iraq formally accepts UN resolution terms for WMD elimination; sanctions continue due to Iraqi obstruction of UNSCOM inspectors','December 1996: Oil-for-Food Program begins, allowing limited oil exports ($2 billion every 6 months) for humanitarian purposes — substantially alleviating civilian suffering but also creating a massive corruption vehicle','December 1998: Operation Desert Fox — US/UK air campaign after Iraq expels UNSCOM inspectors; inspections suspended, sanctions maintained without effective verification mechanism'],
  'Sanctions lifted May 22, 2003 following US-led invasion that toppled Saddam Hussein''s government. WMD programs were not found. Retrospective analysis concluded Iraq had terminated most WMD programs by the late 1990s under sanctions pressure, but this was not verifiable due to Iraqi obstruction.',
  ARRAY['Comprehensive sanctions impose catastrophic humanitarian costs on civilian populations while political elites insulate themselves through corruption and black markets — the Iraq case prompted the UN to shift toward targeted smart sanctions after 2003','Large-scale humanitarian exemptions (Oil-for-Food) inevitably create corruption vectors that simultaneously reduce civilian suffering and provide the sanctioned regime with revenue streams for evasion','Sanctions succeeded in destroying Iraq''s WMD programs but this success was invisible to the international community due to regime opacity, contributing to the intelligence failure that justified the 2003 invasion'],
  ARRAY['Iraq','Gulf War','comprehensive','UN','Oil-for-Food','humanitarian','WMD'],
  ARRAY['https://en.wikipedia.org/wiki/International_sanctions_against_Iraq','UN Oil-for-Food Programme inquiry (Volcker Report)','UNICEF 1999 child mortality estimates'],
  'https://en.wikipedia.org/wiki/International_sanctions_against_Iraq',
  'The most comprehensive UN sanctions regime prior to the 2022 Russia package. GDP fell 75%, oil exports dropped 95%. The Oil-for-Food Program (1996-2003) was corrupted by $1.7 billion in kickbacks, illustrating the structural tension between humanitarian exceptions and regime evasion. Sanctions destroyed Iraq''s WMD programs but the success was opaque, contributing to the 2003 intelligence failure. The humanitarian catastrophe (hundreds of thousands of excess child deaths per UNICEF) catalyzed the shift to "smart sanctions" doctrine after 2003.'
),

-- 7. Libya Gaddafi 1986
(
  'LBY1986_LOCKERBIE',
  'Libya/Gaddafi Terrorism and Lockerbie Sanctions',
  '1986-01-07', '2004-09-20',
  ARRAY['US','UN'],
  'Libya', 0.15, 'comprehensive',
  ARRAY['Force Libya to extradite Lockerbie suspects, accept responsibility for terrorist acts, pay compensation to victims'' families, and cease state sponsorship of terrorism'],
  true, true, 'high',
  ARRAY['US comprehensive trade embargo (January 1986) banning all imports and exports','Freeze on Libyan government assets in the US','Ban on US citizens traveling to or doing business in Libya','UN arms embargo and flight ban (Resolution 748, March 1992)','UN ban on sales of aircraft parts and oil equipment','Diplomatic isolation (UN Resolution 883, November 1993 froze additional assets)'],
  'US sanctions triggered by Libyan sponsorship of terrorism (1986 Berlin disco bombing, Rome/Vienna airport attacks). UN sanctions triggered by Libya''s refusal to extradite suspects in the December 1988 Lockerbie bombing (Pan Am Flight 103, 270 killed)',
  ARRAY['European oil companies (ENI, Wintershall) continued producing Libyan oil under pre-existing contracts; the UN sanctions exempted ongoing oil production, only restricting new equipment and investment','Continued oil exports through European buyers not covered by the US embargo (which predated the UN multilateral regime)','Malta served as a key transit hub for goods and financial flows into Libya','Gaddafi cultivated African Union relationships and pan-African rhetoric to maintain diplomatic cover and alternative trade relationships'],
  '{"gdp_change_pct": -33, "oil_export_change_pct": -35, "inflation_pct": null, "currency_devaluation_pct": null, "alternative_partners": ["Italy","Germany","Spain","Malta"]}',
  'compliance', 'yes',
  '{"scenarios": [{"label": "compliance", "probability": 0.15}, {"label": "partial_compliance", "probability": 0.35}, {"label": "status_quo", "probability": 0.40}, {"label": "negotiation", "probability": 0.10}], "gdp_impact_pct": -15}',
  '{"scenarios": [{"label": "compliance", "probability": 0.25}, {"label": "partial_compliance", "probability": 0.35}, {"label": "status_quo", "probability": 0.30}, {"label": "negotiation", "probability": 0.10}], "gdp_impact_pct": -33}',
  0.75, 24, 84,
  ARRAY['1992: UN imposes multilateral flight ban and arms embargo — the addition of UN multilateral pressure significantly increases Libya''s isolation beyond what US unilateral sanctions achieved','1999: Following Nelson Mandela and Kofi Annan mediation, Gaddafi agrees to hand over Lockerbie suspects for trial in the Netherlands under Scottish law — UN sanctions immediately suspended','2003: Libya formally accepts responsibility for Lockerbie, agrees to pay $2.7 billion compensation, and announces voluntary WMD program termination — all remaining sanctions lifted'],
  'UN sanctions suspended April 1999 when suspects transferred for trial. US sanctions progressively lifted 2003-2004 after Libya accepted Lockerbie responsibility, paid compensation, and voluntarily abandoned WMD programs. Often cited as a successful case of coercive diplomacy.',
  ARRAY['Multilateral UN sanctions are qualitatively more effective than unilateral US sanctions — Gaddafi endured 6 years of US unilateral pressure (1986-1992) without major concessions, but within 7 years of UN multilateral action agreed to hand over suspects','Mediation by respected neutral parties (Mandela, Annan) provided Gaddafi a face-saving diplomatic off-ramp that bilateral US-Libya negotiations could not offer','Targeted compliance asks (extradite two suspects, pay compensation) are more achievable than regime-change objectives — the Libya case succeeded partly because the demands were specific and verifiable'],
  ARRAY['Libya','terrorism','Lockerbie','WMD','successful','multilateral','Africa'],
  ARRAY['https://en.wikipedia.org/wiki/Pan_Am_Flight_103','Volcker Committee Libya sanctions assessment','UN Security Council Resolutions 748, 883'],
  'https://en.wikipedia.org/wiki/Pan_Am_Flight_103',
  'Libya/Gaddafi sanctions represent one of the clearest success cases in the dataset. US unilateral sanctions (1986-1992) failed for 6 years; the addition of UN multilateral pressure in 1992 produced results within 7 years. Gaddafi handed over Lockerbie suspects in 1999, accepted responsibility and paid $2.7 billion compensation in 2003, and voluntarily abandoned WMD programs. Key lessons: multilateral > unilateral, face-saving off-ramps matter, and specific verifiable demands outperform regime-change goals.'
),

-- 8. Venezuela 2019
(
  'VEN2019_MADURO',
  'Venezuela PDVSA and Maduro Government Sanctions',
  '2019-01-28', NULL,
  ARRAY['US','EU','Canada'],
  'Venezuela', 0.28, 'energy_finance',
  ARRAY['Force democratic transition — specifically, compel Maduro to step down and allow free elections under the interim government recognized by 50+ countries'],
  true, false, 'critical',
  ARRAY['OFAC designation of PDVSA (January 28, 2019) blocking all US transactions','Full embargo on PDVSA oil transactions with US entities','Asset freeze on Venezuelan government property in US jurisdiction','Secondary sanctions on third parties transacting with PDVSA','Sanctions on individuals including Maduro, vice president, military officials','Restrictions on gold and cryptocurrency transactions by Venezuelan government','EU travel bans and asset freezes on named Venezuelan officials'],
  'Maduro''s fraudulent 2018 re-election and refusal to hold free elections; support for opposition leader Juan Guaidó''s claim to the presidency',
  ARRAY['Rosneft (Russia) acted as broker for Venezuelan oil sales, funneling cash from petroleum sales through Russian intermediaries to shield transactions from US jurisdiction','Shadow fleet of aging tankers (assisted by Iranian expertise) transporting Venezuelan crude to Chinese buyers outside Western monitoring','Oil-for-debt-service arrangements with China, where crude deliveries were credited against existing loans rather than generating sanctionable cash transactions','Gold exports through Turkey and UAE, often involving Maduro-linked armed groups (colectivos) controlling mines','Cryptocurrency (petro) attempted as dollar-alternative, though with very limited adoption'],
  '{"gdp_change_pct": -35, "oil_export_change_pct": -73, "inflation_pct": 9585, "currency_devaluation_pct": null, "alternative_partners": ["China","Russia","Iran","Cuba","Turkey"]}',
  'evasion', 'no',
  '{"scenarios": [{"label": "regime_change", "probability": 0.15}, {"label": "status_quo", "probability": 0.55}, {"label": "negotiated_transition", "probability": 0.20}, {"label": "sanctions_relief", "probability": 0.10}], "gdp_impact_pct": -18}',
  '{"scenarios": [{"label": "regime_change", "probability": 0.10}, {"label": "status_quo", "probability": 0.60}, {"label": "negotiated_transition", "probability": 0.15}, {"label": "sanctions_relief", "probability": 0.15}], "gdp_impact_pct": -35}',
  0.12, 3, NULL,
  ARRAY['January 2019: PDVSA designation triggers immediate collapse in US-refined petroleum sales; Venezuelan oil production falls from 1.2 million b/d to 324,000 b/d by September 2020','Early 2020: US designates Rosneft Trading for facilitating Venezuelan oil sales; Russia replaces it with new subsidiaries, demonstrating sanctions whack-a-mole dynamics','2020-2021: Guaidó parallel government loses international recognition momentum; Maduro consolidates power despite maximum economic pressure — GDP contracts 75% cumulatively 2014-2021'],
  'Ongoing as of March 2026. Maduro remains in power. Guaidó''s parallel government dissolved January 2023 after losing international support. US issued partial sanctions relief for PDVSA transactions (October 2023 Barbados Agreement) conditioned on electoral concessions — revoked six months later when Maduro failed to implement commitments.',
  ARRAY['Sanctions that target an oil sector already devastated by mismanagement compound civilian suffering without gaining additional coercive leverage over a regime whose political survival depends on military loyalty rather than economic performance','The Rosneft episode demonstrates that sanctioning a third-country state oil company creates diplomatic costs with a major power that may exceed the sanctions benefit','Oil-for-debt arrangements with China represent a structurally sanctions-proof financing mechanism that Western governments have no legal basis to block'],
  ARRAY['Venezuela','oil','PDVSA','democracy','Maduro','Latin America'],
  ARRAY['https://en.wikipedia.org/wiki/United_States_sanctions_during_the_Venezuelan_crisis','OFAC Venezuela sanctions 2019','US Treasury PDVSA designation'],
  'https://en.wikipedia.org/wiki/United_States_sanctions_during_the_Venezuelan_crisis',
  'Maximum-pressure sanctions on Venezuela''s oil sector (2019) achieved massive economic damage — oil production fell 73%, inflation hit 9,585%, GDP contracted a cumulative 75%. But Maduro remained in power, sustained by military loyalty, Russian brokerage of oil sales, and Chinese oil-for-debt arrangements. The Guaidó parallel government collapsed in 2023. Classic case of sanctions imposing civilian suffering without achieving political transition in a petrostate where regime survival depends on security force loyalty rather than economic performance.'
),

-- 9. Myanmar 2021
(
  'MMR2021_COUP',
  'Myanmar Military Junta (Tatmadaw) Post-Coup Sanctions',
  '2021-02-01', NULL,
  ARRAY['US','EU','UK','Canada','Australia'],
  'Myanmar', 0.06, 'finance_defense',
  ARRAY['Restore civilian democratic governance; hold military accountable for human rights atrocities; pressure military to release political prisoners including Aung San Suu Kyi'],
  true, false, 'medium',
  ARRAY['Asset freezes and travel bans on Senior General Min Aung Hlaing and military leadership','Sanctions on Myanmar Economic Holdings Ltd (MEHL) and Myanmar Economic Corporation (MEC) — the two main military conglomerates','US sanctions on Myanmar Oil and Gas Enterprise (MOGE)','Restrictions on gem exports (rubies, jade)','Arms embargo by US, EU, UK','Ban on imports from military-linked enterprises','Export controls on US-origin technology'],
  'Military coup on February 1, 2021, overthrowing the elected government of Aung San Suu Kyi and the National League for Democracy; mass killing of protesters',
  ARRAY['Aviation fuel import via intermediaries — direct sales fell sharply post-sanctions but shipping data reveals an intermediary layer acquiring jet fuel in Singapore and Thailand for Myanmar military','China developing a Myanmar Central Bank digital currency linked to CIPS, potentially creating a backdoor into the global financial system for sanctioned entities','MOGE continued selling natural gas to Thailand and China under long-term contracts exempted from Western sanctions; revenue flows to the military','Myanmar Foreign Trade Bank shifted international transfer operations to Myanmar Economic Bank immediately after US sanction of the former','Arms procurement from Russia and China continuing unimpeded given neither participates in Western arms embargo'],
  '{"gdp_change_pct": -18, "oil_export_change_pct": null, "inflation_pct": 25.4, "currency_devaluation_pct": 70, "alternative_partners": ["China","Russia","Thailand","India","Singapore"]}',
  'ongoing', 'no',
  '{"scenarios": [{"label": "compliance", "probability": 0.03}, {"label": "escalation", "probability": 0.55}, {"label": "status_quo", "probability": 0.35}, {"label": "negotiation", "probability": 0.07}], "gdp_impact_pct": -8}',
  '{"scenarios": [{"label": "compliance", "probability": 0.03}, {"label": "escalation", "probability": 0.60}, {"label": "status_quo", "probability": 0.30}, {"label": "negotiation", "probability": 0.07}], "gdp_impact_pct": -18}',
  0.07, 6, NULL,
  ARRAY['February 2021: Coup triggers immediate Western sanctions, but China and India — Myanmar''s largest trading partners — decline to join, critically limiting economic pressure','2023: Junta faces unprecedented military losses to resistance forces; economic collapse (18% GDP contraction) weakens military logistics without changing political calculus','2024-2025: Resistance forces capture significant territory; junta increasingly reliant on Russian and Chinese arms; Western sanctions have not translated into political leverage'],
  'Ongoing as of March 2026. Civil war continues. Military government controls major cities but faces substantial territorial losses. Sanctions have contributed to economic collapse but not regime change.',
  ARRAY['Targeted sanctions against military conglomerates are less effective when those conglomerates derive most revenue from domestic markets or trade with non-participating neighbors (China, Thailand, India)','Coordination failures among Western sanctioners create exploitable gaps — lack of a UN Security Council mandate (blocked by China and Russia) means Myanmar junta accesses Russian and Chinese arms markets without restriction','Aviation fuel as a targeted commodity is promising but enforcement requires sanctioning intermediaries in Singapore and Thailand, creating diplomatic frictions that participating governments have been unwilling to accept'],
  ARRAY['Myanmar','Burma','coup','military','arms-embargo','ASEAN'],
  ARRAY['https://en.wikipedia.org/wiki/2021_Myanmar_coup_d%27%C3%A9tat','US Treasury OFAC Myanmar designations 2021-2024','UN Special Rapporteur Myanmar reports'],
  'https://en.wikipedia.org/wiki/2021_Myanmar_coup_d%27%C3%A9tat',
  'Western sanctions on Myanmar''s military junta following the February 2021 coup have produced significant economic damage (GDP -18%, currency -70%) without achieving political transition. China and India — the two largest trading partners — declined to participate, creating structural evasion routes. The military conglomerates MEHL and MEC remain operational through domestic revenue. The case illustrates how partial multilateral sanctions with major-power non-participation fail against a regime willing to accept civilian suffering.'
),

-- 10. South Africa Apartheid 1986
(
  'ZAF1986_APARTHEID',
  'South Africa Apartheid Sanctions',
  '1986-10-02', '1993-09-01',
  ARRAY['US','EU','Commonwealth','UN'],
  'South Africa', 0.50, 'trade_finance',
  ARRAY['Pressure the South African government to end apartheid, release political prisoners (Nelson Mandela), and negotiate a democratic transition'],
  true, true, 'high',
  ARRAY['US Comprehensive Anti-Apartheid Act (1986): ban on new investment, bank loans, South African Airways, imports of certain goods (iron, steel, uranium, agricultural products)','Commonwealth Gleneagles Agreement (1977): sports boycott','EU ban on oil exports to South Africa and imports of iron, steel, gold coins','UN voluntary arms embargo (1963), made mandatory (Resolution 418, 1977)','Disinvestment campaign: 26+ US states, 90+ US cities passed binding economic actions against companies doing business in South Africa','Cultural boycott'],
  'South Africa''s apartheid system of racial segregation and political disenfranchisement; immediate trigger for 1986 US legislation was declaration of state of emergency and crackdown on anti-apartheid movement',
  ARRAY['South African government secretly developed a domestic oil-from-coal (Sasol) industry to reduce petroleum import dependence — sanctions inadvertently accelerated domestic energy independence','Nuclear program developed domestically (six bombs built by 1989) as deterrent; arms embargo circumvented through Israel, Taiwan, and covert procurement networks','Oil imports routed through Oman, UAE, and triangulated via third-country intermediaries despite the oil embargo','Sanctions-busting through Swiss banking secrecy for financial transactions','Many sanctioning countries'' corporations maintained operations through local subsidiaries nominally owned by South African partners'],
  '{"gdp_change_pct": -1.5, "oil_export_change_pct": null, "inflation_pct": 18.6, "currency_devaluation_pct": 35, "alternative_partners": ["Switzerland","Taiwan","Israel","Japan"]}',
  'compliance', 'partial',
  '{"scenarios": [{"label": "compliance", "probability": 0.25}, {"label": "partial_compliance", "probability": 0.40}, {"label": "status_quo", "probability": 0.30}, {"label": "escalation", "probability": 0.05}], "gdp_impact_pct": -1.5}',
  '{"scenarios": [{"label": "compliance", "probability": 0.35}, {"label": "partial_compliance", "probability": 0.40}, {"label": "status_quo", "probability": 0.20}, {"label": "escalation", "probability": 0.05}], "gdp_impact_pct": -1.5}',
  0.78, 18, 84,
  ARRAY['1985: Chase Manhattan Bank refuses to roll over South African loans, triggering a financial crisis as other banks follow — the private financial sector withdrawal was more economically damaging than government sanctions','February 1990: De Klerk unbans ANC, releases Mandela — political opening occurs after sustained economic pressure and internal resistance, though causation debated','September 1993: Mandela personally calls for international sanctions to be lifted; transition to democracy confirmed by all-party negotiations and 1994 election date set'],
  'Sanctions progressively lifted 1993-1994 as South Africa transitioned to democracy. First non-racial elections held April 1994, Mandela elected president. Case frequently cited as evidence that sanctions worked, though academic debate continues about relative weight of sanctions vs. internal resistance.',
  ARRAY['Private-sector financial actors (banks refusing loans, corporations divesting) can be more economically powerful than government-mandated trade sanctions; the 1985 debt crisis was triggered not by legislation but by Chase Manhattan''s risk calculation','Sanctions effectiveness is highly path-dependent — they arguably tipped the balance by strengthening the negotiating hand of reform-minded South African business leaders and white moderates rather than directly coercing the government','The apartheid case is regularly overgeneralized as a sanctions success template; its unique features (democratic pressure from within the white electorate, corporate vulnerability to consumer boycotts, Mandela''s moral authority) do not transfer to authoritarian states without domestic civil society'],
  ARRAY['South Africa','apartheid','arms-embargo','divestment','successful','Africa'],
  ARRAY['https://en.wikipedia.org/wiki/International_sanctions_during_apartheid','US Comprehensive Anti-Apartheid Act 1986','Commonwealth Gleneagles Agreement 1977'],
  'https://en.wikipedia.org/wiki/International_sanctions_during_apartheid',
  'The South Africa apartheid sanctions case (1986-1993) is the most-cited "success" in the sanctions literature but requires careful interpretation. GDP fell only 1.5% but the 1985 Chase Manhattan bank refusal to roll over loans triggered a private-sector financial crisis more damaging than government sanctions. Mandela was released in 1990 and the transition to democracy completed by 1994. Success was highly path-dependent on internal white-electorate democratic pressure, corporate consumer boycott vulnerability, and Mandela''s unique moral authority — features not replicable in authoritarian contexts.'
),

-- 11. Zimbabwe Mugabe 2002
(
  'ZWE2002_MUGABE',
  'Zimbabwe Mugabe/ZANU-PF Targeted Sanctions',
  '2002-02-18', NULL,
  ARRAY['US','EU','Canada','Australia'],
  'Zimbabwe', 0.02, 'finance',
  ARRAY['Pressure Zimbabwe to restore rule of law, respect property rights, hold free elections, and end political violence'],
  true, false, 'medium',
  ARRAY['US Zimbabwe Democracy and Economic Recovery Act (ZIDERA, 2001) — blocks Zimbabwe''s access to international financial institutions','EU asset freezes and travel bans on Mugabe and 145 officials (2002)','Arms embargo','Suspension of Zimbabwe from Commonwealth (2002), formal withdrawal 2003','Asset freezes on ZANU-PF-linked individuals and entities','Restrictions on trade preferences'],
  'Mugabe''s fast-track land reform program (2000) involving violent seizure of white-owned farms; rigged 2000 and 2002 elections; political violence against opposition MDC',
  ARRAY['China provided diplomatic cover, loans, and trade links outside Western financial system; ZANU-PF secured Chinese investment in mining and agriculture as Western capital fled','Mugabe regime accessed diamond revenues from Marange fields (discovered 2006) outside Western financial oversight, generating cash outside sanctioned channels','Russia and Belarus supplied arms in circumvention of the EU arms embargo','South Africa as Zimbabwe''s dominant trading partner declined to participate in sanctions, providing essential economic lifeline for basic goods','ZANU-PF elites held assets through intermediaries in Mozambique, Malaysia, and UAE'],
  '{"gdp_change_pct": -40, "oil_export_change_pct": null, "inflation_pct": 79600000000, "currency_devaluation_pct": null, "alternative_partners": ["China","South Africa","Russia"]}',
  'stalemate', 'no',
  '{"scenarios": [{"label": "compliance", "probability": 0.05}, {"label": "status_quo", "probability": 0.60}, {"label": "economic_collapse", "probability": 0.30}, {"label": "negotiation", "probability": 0.05}], "gdp_impact_pct": -10}',
  '{"scenarios": [{"label": "compliance", "probability": 0.04}, {"label": "status_quo", "probability": 0.55}, {"label": "economic_collapse", "probability": 0.35}, {"label": "negotiation", "probability": 0.06}], "gdp_impact_pct": -40}',
  0.11, 12, NULL,
  ARRAY['2008: Hyperinflation reaches an estimated 79.6 billion percent in November; Zimbabwe effectively dollarizes informally as the Zimbabwe dollar becomes worthless — economic collapse without political change','2009: GNU (Government of National Unity) formed between ZANU-PF and MDC; Zimbabwe adopts multi-currency system (primarily USD), ending hyperinflation — not a result of sanctions but of internal political accommodation','2017: Mugabe ousted by military; Mnangagwa takes power — EU partially lifts sanctions on individuals 2012, remaining sanctions lifted 2020 for most individuals'],
  'Mugabe died 2019. EU lifted most individual sanctions in 2020-2023 after reviewing evidence of reform. US ZIDERA remains partially in effect. Zimbabwe under Mnangagwa continues to face targeted sanctions for ongoing human rights concerns. Economy remains severely distressed.',
  ARRAY['Targeted sanctions (individuals, not economy) failed to coerce Zimbabwe because ZANU-PF elites were insulated from economic pain; hyperinflation was caused overwhelmingly by domestic monetary policy rather than external sanctions','When a sanctioned state''s dominant neighbor (South Africa) declines to participate, land-based trade sanctions are effectively impossible to enforce','Sanctions and domestic misgovernance can create a dual causation problem in attribution: Zimbabwe''s economic catastrophe was so driven by internal policy failures that sanctions provided rhetorical cover rather than being the primary cause'],
  ARRAY['Zimbabwe','Mugabe','hyperinflation','targeted','Africa','land-reform'],
  ARRAY['https://en.wikipedia.org/wiki/Economy_of_Zimbabwe','US ZIDERA 2001','EU Zimbabwe sanctions 2002-2020'],
  'https://en.wikipedia.org/wiki/Economy_of_Zimbabwe',
  'Zimbabwe targeted sanctions (2002-ongoing) are a cautionary tale about attribution failure. GDP fell 40% and inflation reached 79.6 billion percent — but these were driven primarily by Mugabe''s domestic monetary mismanagement, not external sanctions. ZANU-PF elites were insulated from pain via Chinese investment, diamond revenues, and South African trade lifeline. The sanctions provided Mugabe with a convenient external scapegoat while failing to change behavior. Mugabe was eventually removed by his own military in 2017, not by sanctions pressure.'
),

-- 12. Belarus 2020
(
  'BLR2020_LUKASHENKO',
  'Belarus Lukashenko Post-Election Sanctions',
  '2020-10-01', NULL,
  ARRAY['US','EU','UK','Canada'],
  'Belarus', 0.07, 'finance_energy',
  ARRAY['Press Lukashenko to hold free elections, release political prisoners, and cease violent repression of civil society'],
  true, false, 'high',
  ARRAY['Asset freezes and travel bans on Lukashenko and 200+ officials','EU sanctions on major Belarusian industries: potash, petroleum products, tobacco, steel','Ban on Belarusian state airline Belavia from EU airspace (after forced Ryanair diversion, 2021)','US sanctions on Belarusian potash company Belaruskali','EU ban on importing Belarusian potash (effective 2022)','Prohibition on export of dual-use technology'],
  'Disputed August 2020 presidential election (Lukashenko declared winner against credible evidence of fraud); violent crackdown on massive post-election protests; arrest of journalist Roman Protasevich after forcing Ryanair diversion in May 2021',
  ARRAY['Sanctioned Belarusian goods (potash, petroleum products) re-routed through Russia and Kazakhstan with falsified certificates of origin','SPFS (Russian financial messaging system) linked to Belarusian banks, enabling payments to bypass SWIFT for Russia-Belarus transactions','Western goods sanctioned for export to Russia re-exported via Belarusian intermediaries with forged documentation showing Belarusian end-use','Goods shipped to Belarus from EU then re-routed to Russia after crossing border, exploiting Belarus-Russia customs union','Belarusian oligarchs and regime elites transferred assets to UAE, Turkey, and Dubai-based fronts'],
  '{"gdp_change_pct": -4.7, "oil_export_change_pct": null, "inflation_pct": 12.8, "currency_devaluation_pct": 30, "alternative_partners": ["Russia","China","Kazakhstan","Turkey","UAE"]}',
  'ongoing', 'no',
  '{"scenarios": [{"label": "compliance", "probability": 0.05}, {"label": "status_quo", "probability": 0.55}, {"label": "escalation", "probability": 0.30}, {"label": "negotiation", "probability": 0.10}], "gdp_impact_pct": -2.5}',
  '{"scenarios": [{"label": "compliance", "probability": 0.04}, {"label": "status_quo", "probability": 0.55}, {"label": "escalation", "probability": 0.35}, {"label": "negotiation", "probability": 0.06}], "gdp_impact_pct": -4.7}',
  0.09, 12, NULL,
  ARRAY['May 2021: Lukashenko forces Ryanair flight to land in Minsk to arrest journalist Protasevich — triggers the most severe Western sanctions response and EU airspace ban on Belavia','February 2022: Belarus allows Russia to use Belarusian territory to invade Ukraine; deepens Western sanctions but also tightly binds Belarus to Russia as primary economic lifeline','2022-2023: EU potash ban significantly reduces Belarusian hard-currency earnings; Russia compensates by purchasing Belarusian goods and providing preferential energy pricing'],
  'Ongoing as of March 2026. Lukashenko remains in power. Potash export ban has cut one of Belarus''s major revenue streams. Belarus has become economically integrated into Russia as a result of Western sanctions, limiting future Western leverage.',
  ARRAY['Sectoral sanctions targeting potash (Belarus controls ~20% of global supply) are a significant coercive tool but create tension with global food security concerns since potash is an agricultural fertilizer','Belarus demonstrates that sanctions can create perverse integration outcomes: by cutting off Western economic relationships, sanctions pushed Belarus deeper into Russian economic orbit, reducing future Western diplomatic leverage','Belarus-Russia customs union makes enforcing technology export controls extremely difficult — goods legally exported to Belarus are functionally exportable to Russia, requiring secondary sanctions on Belarusian entities that most Western governments have been cautious about applying'],
  ARRAY['Belarus','Lukashenko','election-fraud','potash','Europe','Russia-proxy'],
  ARRAY['https://en.wikipedia.org/wiki/List_of_people_and_organizations_sanctioned_in_relation_to_human_rights_violations_in_Belarus','EU Belarus sanctions packages 2020-2024','US OFAC Belarus designations'],
  'https://en.wikipedia.org/wiki/List_of_people_and_organizations_sanctioned_in_relation_to_human_rights_violations_in_Belarus',
  'Belarus sectoral sanctions (2020-ongoing) illustrate the perverse integration risk: Western sanctions pushed Belarus deeper into Russian economic orbit, reducing future leverage. The potash ban (Belarus controls ~20% of global supply) was a significant tool but raised food security concerns. Russia compensated for all lost Western revenue. The Ryanair forced diversion in 2021 added aviation sanctions. Lukashenko remains in power as of 2026, using Belarus as a transit hub for Russia sanctions evasion under the customs union.'
),

-- 13. China Tiananmen 1989
(
  'CHN1989_TIANANMEN',
  'China Post-Tiananmen Arms Embargo',
  '1989-06-05', NULL,
  ARRAY['US','EU','Canada','Australia','Japan'],
  'China', 1.50, 'defense',
  ARRAY['Signal condemnation of the massacre; pressure China to pursue political liberalization and respect for human rights'],
  true, false, 'medium',
  ARRAY['US arms embargo (Executive Order, June 5, 1989) and Section 902 of Foreign Relations Authorization Act FY1990-91','EU arms embargo (June 1989) — politically agreed but not legally binding in EU law','Suspension of high-level military exchanges','Suspension of US OPIC and TDA programs','World Bank loan suspension (briefly)','Suspension of Munitions List exports from US'],
  'People''s Liberation Army crackdown on pro-democracy demonstrators in Tiananmen Square on June 3-4, 1989, killing hundreds to thousands of civilians',
  ARRAY['Massive domestic defense-industrial buildup: China used the embargo as a forcing function to develop indigenous defense industry, reducing dependence on foreign arms','Russia became primary arms supplier after USSR collapse — sold advanced Su-27/Su-30 fighters, destroyers, submarines, and S-300 missile systems throughout the 1990s-2000s','Israel (before US pressure) supplied Phalcon airborne radar systems and Python-4 missiles; program partially rolled back under US pressure in 2000','Ukraine provided aviation technology (carrier-borne aircraft, turbofan engines) outside Western embargo framework','US itself issued presidential waivers for $350 million in defense transactions to China 1989-1998 per GAO report','EU embargo not legally binding — individual EU member states France and Germany sold dual-use technology with military applications throughout the 1990s'],
  '{"gdp_change_pct": null, "oil_export_change_pct": null, "inflation_pct": null, "currency_devaluation_pct": null, "alternative_partners": ["Russia","Israel","Ukraine","France (partial)"]}',
  'backfire', 'no',
  '{"scenarios": [{"label": "compliance", "probability": 0.02}, {"label": "status_quo", "probability": 0.70}, {"label": "backfire", "probability": 0.28}], "gdp_impact_pct": 0}',
  '{"scenarios": [{"label": "compliance", "probability": 0.01}, {"label": "status_quo", "probability": 0.60}, {"label": "backfire", "probability": 0.39}], "gdp_impact_pct": 0}',
  0.05, NULL, NULL,
  ARRAY['1992-2000s: China-Russia military cooperation fills the embargo gap comprehensively; Russia''s arms sales become a multibillion-dollar annual industry independent of Western controls','2004-2005: EU debates lifting the embargo under Chinese diplomatic pressure and French commercial lobbying; ultimately blocked by US congressional pressure and concerns over Taiwan','2010s-2020s: China achieves near-complete indigenous defense-industrial capacity (J-20 stealth fighter, Type 055 destroyer, DF-21D anti-ship missiles) — the embargo has been comprehensively overcome'],
  'Technically still in force as of March 2026. Functionally meaningless in constraining China''s military development. The EU embargo is under periodic review but remains nominally in place. The US embargo remains statutory. China has publicly called for its removal at every P5 summit.',
  ARRAY['Arms embargoes against large states with significant industrial capacity and alternative suppliers inevitably serve as industrial policy forcing functions — China''s defense sector is arguably stronger today for having been denied Western technology','Non-legally-binding arms embargoes (EU model) lack enforcement mechanisms and credibility — member states exploiting dual-use loopholes effectively hollowed out the embargo without formally violating it','Sanctions against a rapidly growing major economic power carry an escalating opportunity cost over time — the 1989 sanctioners could not anticipate that the target would become the world''s second-largest economy and could credibly threaten counter-coercion'],
  ARRAY['China','arms-embargo','Tiananmen','human-rights','backfire','longest-running'],
  ARRAY['https://en.wikipedia.org/wiki/1989_Tiananmen_Square_protests_and_massacre','GAO report on China arms embargo waivers 1989-1998','EU China arms embargo review 2004'],
  'https://en.wikipedia.org/wiki/1989_Tiananmen_Square_protests_and_massacre',
  'The China/Tiananmen arms embargo (1989-present) is the defining backfire case in arms embargo literature. Technically still in force 35+ years later, it is functionally meaningless: China filled the gap with Russian arms, developed indigenous defense industry (J-20, Type 055), and became the world''s largest arms importer then major defense-industrial power. The EU embargo was non-binding, allowing member states to sell dual-use technology throughout. The embargo accelerated Chinese defense-industrial self-sufficiency rather than constraining it.'
),

-- 14. Yugoslavia Serbia 1992
(
  'YUG1992_SERBIA',
  'Yugoslavia/Serbia UN Comprehensive Sanctions',
  '1992-05-30', '1995-11-22',
  ARRAY['UN','US','EU'],
  'Serbia / Federal Republic of Yugoslavia', 0.10, 'comprehensive',
  ARRAY['Force Serbia to withdraw support from Bosnian Serb forces, cease military aggression, and accept a negotiated settlement to the Yugoslav wars'],
  true, true, 'critical',
  ARRAY['Full trade embargo (UN Resolution 757, May 1992) — one of the most comprehensive UN sanction regimes at that time','Ban on all financial transfers to and from Yugoslavia','Suspension of air traffic','Oil embargo','Arms embargo','Prohibition on scientific, technical, and cultural cooperation','Reduction of diplomatic missions'],
  'Serbia''s military support for ethnic Serbian forces waging war in Bosnia-Herzegovina; Serbian and Montenegrin forces'' siege of Sarajevo and conduct of ethnic cleansing',
  ARRAY['Grey economy grew to 54% of GDP by 1993 — smuggling networks run by organized crime, regime insiders, and security services replaced formal trade','Oil smuggled through Greece via Macedonian intermediaries; gasoline and diesel sold in Greek border regions to Serbian buyers','Romania and Bulgaria served as transit hubs for sanctioned goods entering Yugoslavia through Danube River traffic','Milosevic allies ran state-protected smuggling monopolies — the Arkan criminal-paramilitary network was central to fuel imports','Parallel currency markets and unrecorded remittances from the Yugoslav diaspora sustained household consumption'],
  '{"gdp_change_pct": -60, "oil_export_change_pct": null, "inflation_pct": 116545000000, "currency_devaluation_pct": null, "alternative_partners": ["Greece","Bulgaria","Romania","Russia"]}',
  'partial_compliance', 'partial',
  '{"scenarios": [{"label": "compliance", "probability": 0.10}, {"label": "partial_compliance", "probability": 0.45}, {"label": "status_quo", "probability": 0.35}, {"label": "escalation", "probability": 0.10}], "gdp_impact_pct": -30}',
  '{"scenarios": [{"label": "compliance", "probability": 0.20}, {"label": "partial_compliance", "probability": 0.45}, {"label": "status_quo", "probability": 0.25}, {"label": "escalation", "probability": 0.10}], "gdp_impact_pct": -60}',
  0.45, 6, 42,
  ARRAY['1993: Hyperinflation reaches 116 quadrillion percent — one of the worst in recorded history; GDP falls to one-third of 1990 levels, demonstrating catastrophic economic impact on civilian population','August 1994: Milosevic cuts off support to Bosnian Serbs under sanctions pressure; endorses international peace plan — evidence that economic pain produced policy shift, but insufficient to end the war','November 1995: Dayton Peace Agreement signed; UN Resolution 1022 immediately suspends sanctions after Milosevic''s signature — demonstrating sanctions were tied to specific behavioral demands'],
  'Sanctions suspended November 22, 1995, the day after the Dayton Agreement was initialed. Formally terminated after elections in 1996. The sanctions caused severe humanitarian costs and contributed to one of history''s worst hyperinflations, but the war ended through military pressure (NATO airstrikes, Croatian offensives) as much as economic coercion.',
  ARRAY['Comprehensive sanctions can produce economic devastation (60% GDP decline, hyperinflation) without producing full political compliance — Milosevic maintained power throughout, and war ended primarily through military force rather than economic coercion','State-protected smuggling networks are a predictable evasion response to comprehensive embargoes: Milosevic''s inner circle profited from the black market, partially offsetting their incentive to comply','Tying specific sanctions relief to specific behavioral benchmarks (signing Dayton) provided a clear exit ramp that made Milosevic''s compliance more likely than an open-ended pressure campaign'],
  ARRAY['Yugoslavia','Serbia','Bosnia','UN','comprehensive','war','Balkans'],
  ARRAY['https://en.wikipedia.org/wiki/Sanctions_against_Yugoslavia','UN Security Council Resolution 757 (1992)','Dayton Peace Agreement 1995'],
  'https://en.wikipedia.org/wiki/Sanctions_against_Yugoslavia',
  'Yugoslavia/Serbia comprehensive sanctions (1992-1995) produced devastating economic damage (GDP -60%, inflation of 116 quadrillion percent) but partial compliance only — war ended through NATO airstrikes and Croatian military offensives as much as economic pressure. State-protected smuggling networks (run by Milosevic allies and organized crime) provided partial evasion. The Dayton Agreement''s specific, verifiable behavioral benchmarks tied to sanctions relief provided a clear exit ramp — a model for successful coercive diplomacy.'
),

-- 15. Sudan Darfur 2005
(
  'SDN2005_DARFUR',
  'Sudan/Darfur Targeted Sanctions',
  '2005-03-31', NULL,
  ARRAY['US','UN','EU'],
  'Sudan', 0.04, 'defense',
  ARRAY['End mass atrocities in Darfur; protect civilians; achieve accountability for war crimes; support deployment of AU/UN peacekeeping force (UNAMID)'],
  true, true, 'medium',
  ARRAY['UN arms embargo on all parties in Darfur (Resolution 1556, 2004; expanded 1591, 2005)','Travel bans and asset freezes on designated individuals (Resolution 1591)','US OFAC comprehensive sanctions on Sudan (predating Darfur, imposed 1997; lasted until 2017)','ICC referral of Darfur situation (Resolution 1593, 2005)','ICC arrest warrants for President Bashir (2009, 2010) for genocide, crimes against humanity, war crimes'],
  'Sudanese government and Janjaweed militia campaign against African ethnic groups in Darfur beginning 2003-2004, characterized by the US government as genocide',
  ARRAY['China blocked or diluted multiple UN Security Council resolutions under threat of veto; CNPC invested in Sudanese oil (owning 6 blocks in Darfur area), providing economic lifeline and diplomatic cover simultaneously','Sudanese government circumvented arms embargo by obtaining weapons designated for police rather than military use; Chinese and Russian arms suppliers complied with letter but not spirit of restrictions','Khartoum reclassified Janjaweed militia as Border Intelligence forces to avoid arms embargo applicability','US comprehensive sanctions (pre-2017) were partially undermined by the fact that Sudan''s oil exports went almost entirely to China, not the US, minimizing actual trade impact','ICC arrest warrants for Bashir proved unenforceable — Bashir traveled to multiple AU member states that refused to detain him'],
  '{"gdp_change_pct": null, "oil_export_change_pct": null, "inflation_pct": null, "currency_devaluation_pct": null, "alternative_partners": ["China","Russia","Gulf States","Malaysia"]}',
  'stalemate', 'no',
  '{"scenarios": [{"label": "compliance", "probability": 0.05}, {"label": "status_quo", "probability": 0.65}, {"label": "escalation", "probability": 0.25}, {"label": "ICC_accountability", "probability": 0.05}], "gdp_impact_pct": 0}',
  '{"scenarios": [{"label": "compliance", "probability": 0.04}, {"label": "status_quo", "probability": 0.65}, {"label": "escalation", "probability": 0.25}, {"label": "ICC_accountability", "probability": 0.06}], "gdp_impact_pct": 0}',
  0.09, NULL, NULL,
  ARRAY['2005: ICC referral — unprecedented use of Security Council authority to mandate ICC jurisdiction over a non-ICC member state; Bashir becomes first sitting head of state indicted by ICC (2009)','2010: Bashir attends AU Summit in Kenya, Chad, and Djibouti — all ICC members that refuse to arrest him; demonstrates limits of international criminal justice enforcement','2011: South Sudan secession removes 75% of Sudan''s oil production from Khartoum''s control; greater economic shock than Western sanctions ever imposed'],
  'Ongoing. US lifted comprehensive Sudan sanctions in 2017 based on counterterrorism cooperation. Darfur-specific sanctions remain. Bashir was ousted in 2019 Sudan coup; Sudan''s transitional government surrendered him to the ICC in 2021. Darfur conflict reignited in Sudan''s 2023 civil war between SAF and RSF.',
  ARRAY['Security Council referrals to the ICC create long-term accountability mechanisms but have no immediate coercive effect on ongoing atrocities — the Darfur case shows that criminal prosecution and conflict prevention operate on different timescales','When the target''s primary economic relationship (Sudan-China oil) is with a Security Council veto-holder, UN-based sanctions will be systematically blocked or diluted, making the UN channel largely irrelevant','Arms embargoes in active conflict zones with porous borders and multiple armed non-state actors are nearly impossible to enforce — weapons flow through conflict region borders regardless of Security Council mandate'],
  ARRAY['Sudan','Darfur','genocide','ICC','arms-embargo','Africa','China-veto'],
  ARRAY['https://en.wikipedia.org/wiki/Sudan_and_Darfur_sanctions','UN Security Council Resolution 1593 (2005)','ICC Case The Prosecutor v. Omar Hassan Ahmad Al-Bashir'],
  'https://en.wikipedia.org/wiki/Sudan_and_Darfur_sanctions',
  'Sudan/Darfur sanctions illustrate the structural failure of UN-based pressure when the target''s primary economic partner holds a Security Council veto. China (CNPC invested in Darfur oil blocks) blocked/diluted multiple resolutions. The ICC referral created landmark legal accountability — Bashir became the first sitting head of state indicted for genocide — but proved unenforceable as AU members refused to arrest him. Arms embargoes in active conflict zones with porous borders are unenforceable without ground enforcement mechanisms.'
),

-- 16. Rhodesia UDI 1965
(
  'RHO1965_UDI',
  'Rhodesia UDI Sanctions',
  '1965-11-12', '1979-12-21',
  ARRAY['UN','UK','Commonwealth'],
  'Rhodesia (Zimbabwe Rhodesia)', 0.02, 'trade',
  ARRAY['Force Rhodesia to rescind UDI and return to British authority; subsequently achieve majority-rule democratic government as a precondition for independence'],
  true, true, 'high',
  ARRAY['British oil embargo (December 17, 1965) immediately after UDI','UN Security Council voluntary sanctions (Resolution 217, 1965)','UN mandatory comprehensive sanctions (Resolution 253, 1968) — first time UNSC used mandatory sanctions under Chapter VII','Arms embargo','Ban on import of Rhodesian goods (tobacco, chrome, sugar, meat)','Prohibition on financial transactions'],
  'Ian Smith''s Rhodesian government''s Unilateral Declaration of Independence (UDI) from Britain on November 11, 1965, to avoid majority-rule Black African governance',
  ARRAY['South Africa — sharing a long border and opposing majority-rule precedent — explicitly refused to join sanctions and supplied fuel, goods, and financial services throughout the sanctions period','Portugal facilitated oil imports through Mozambican ports of Beira and Lourenço Marques until Portugal''s 1974 Carnation Revolution ended colonial rule','The US Congress passed the Byrd Amendment (1971) exempting chrome imports from Rhodesia on national security grounds — demonstrating sanctions-busting within the sanctioning coalition itself','Rhodesia rapidly diversified its economy away from tobacco toward manufacturing and import substitution under sanctions pressure','Swiss banking secrecy enabled Rhodesian financial transactions with European counterparties'],
  '{"gdp_change_pct": null, "oil_export_change_pct": null, "inflation_pct": null, "currency_devaluation_pct": null, "alternative_partners": ["South Africa","Portugal (Mozambique)","US (chrome imports 1971-77)","Switzerland"]}',
  'compliance', 'partial',
  '{"scenarios": [{"label": "compliance", "probability": 0.05}, {"label": "status_quo", "probability": 0.65}, {"label": "evasion", "probability": 0.30}], "gdp_impact_pct": -5}',
  '{"scenarios": [{"label": "compliance", "probability": 0.08}, {"label": "status_quo", "probability": 0.60}, {"label": "evasion", "probability": 0.32}], "gdp_impact_pct": -8}',
  0.55, 12, 168,
  ARRAY['1974: Portuguese Carnation Revolution ends colonial rule in Mozambique; Mozambique under Frelimo closes its border with Rhodesia (1976), eliminating a critical sanctions-busting corridor and access to Indian Ocean ports','1976: US repeals Byrd Amendment, closing the chrome import loophole and finally bringing the US into full compliance with mandatory UN sanctions','1979: Lancaster House Agreement negotiated in London — Smith government accepts majority-rule elections; sanctions lifted; Zimbabwe independence declared April 1980'],
  'Rhodesian government accepted Lancaster House Agreement in December 1979 after 14 years of resistance. Free elections held February 1980; Robert Mugabe''s ZANU won. Sanctions lifted. The case is debated: economic pressure was significant but the decisive factors may have been South Africa withdrawing support and intensifying guerrilla warfare by ZANU/ZAPU forces.',
  ARRAY['Contiguous neighbor defection is the single largest predictor of sanctions failure — South Africa''s explicit refusal to participate sustained Rhodesia for 14 years despite otherwise broad multilateral support','The Byrd Amendment case demonstrates that domestic commercial interests within sanctioning countries will consistently seek exemptions, eroding the economic impact even of mandatory UN sanctions','The eventual success of Rhodesia sanctions was heavily dependent on external geopolitical shifts (Portuguese decolonization, South African policy change) rather than pure economic coercion dynamics'],
  ARRAY['Rhodesia','Zimbabwe','UDI','mandatory-sanctions','UN-chapter-VII','Africa','Cold-War'],
  ARRAY['https://en.wikipedia.org/wiki/Rhodesia%27s_Unilateral_Declaration_of_Independence','UN Security Council Resolution 253 (1968)','Lancaster House Agreement 1979'],
  'https://en.wikipedia.org/wiki/Rhodesia%27s_Unilateral_Declaration_of_Independence',
  'Rhodesia UDI sanctions (1965-1979) are the first case of mandatory UN Chapter VII sanctions and demonstrate the decisive role of neighboring state compliance. South Africa''s explicit refusal to participate sustained Rhodesia for 14 years. Decisive factors were external: the 1974 Portuguese Carnation Revolution closed the Mozambique sanctions-busting corridor, and South Africa eventually withdrew support under its own pressures. The Byrd Amendment illustrated how domestic commercial interests erode even mandatory sanctions within the coalition.'
),

-- 17. Italy Abyssinia 1935
(
  'ITA1935_ABYSSINIA',
  'League of Nations Sanctions Against Italy (Abyssinia Crisis)',
  '1935-10-11', '1936-07-04',
  ARRAY['League of Nations (50 member states)'],
  'Italy', 1.00, 'trade',
  ARRAY['Compel Italy to withdraw from Abyssinia; uphold collective security principles and the League Covenant prohibition on aggressive war'],
  true, false, 'medium',
  ARRAY['Arms embargo on Italy','Ban on loans and credit to Italy','Import ban on Italian goods by 50 League members','Export restrictions on certain raw materials to Italy (rubber, tin, some metals)','NOT included: oil embargo (proposed but rejected), coal embargo, steel embargo'],
  'Italy''s invasion of Abyssinia (Ethiopia) on October 3, 1935 — the first major test of the League''s collective security system',
  ARRAY['United States (not a League member) was the world''s largest oil producer and its neutrality legislation prevented Roosevelt from imposing an oil embargo; American oil companies increased exports to Italy fivefold during the crisis','Germany (expelled from League 1933) continued trading with Italy outside the sanctions framework; the Rome-Berlin Axis announced October 1936 reflected this alignment','The Hoare-Laval Pact (December 1935) — secret Anglo-French agreement offering Italy most of Abyssinia in exchange for ending the war — revealed that Britain and France were unwilling to enforce sanctions militarily','Oil was deliberately excluded from League sanctions despite being Italy''s most critical import — coal and iron were also excluded; the sanctions omitted Italy''s most vulnerable supply chains'],
  '{"gdp_change_pct": null, "oil_export_change_pct": null, "inflation_pct": null, "currency_devaluation_pct": null, "alternative_partners": ["United States","Germany","Austria","Hungary"]}',
  'backfire', 'no',
  '{"scenarios": [{"label": "compliance", "probability": 0.10}, {"label": "status_quo", "probability": 0.50}, {"label": "backfire", "probability": 0.40}], "gdp_impact_pct": -1}',
  '{"scenarios": [{"label": "compliance", "probability": 0.05}, {"label": "status_quo", "probability": 0.30}, {"label": "backfire", "probability": 0.65}], "gdp_impact_pct": 0}',
  0.03, 3, 8,
  ARRAY['December 1935: Hoare-Laval Pact revealed — France and Britain secretly planned to partition Abyssinia giving Italy the best agricultural regions; massive public outrage forces both Foreign Ministers to resign but fatally exposes allied bad faith','May 1936: Italy completes conquest of Abyssinia; Emperor Haile Selassie addresses League Assembly — sanctions are suspended July 1936 as Italy annexes Ethiopia and League accepts fait accompli','October 1936: Rome-Berlin Axis announced; Mussolini draws strategic conclusion from the episode that Western democracies will not enforce international law — reinforcing the path toward WWII'],
  'Sanctions suspended July 4, 1936 after Italy formally annexed Ethiopia. The episode destroyed the League of Nations'' credibility as a collective security institution. The failure to include oil in sanctions — the one commodity that could have halted Italian military operations — is regarded as the decisive political failure.',
  ARRAY['Sanctions that deliberately exclude the target''s most critical import (oil) in a war scenario are not just ineffective but may be counterproductive — they signal resolve without imposing meaningful costs, credibly demonstrating Western irresolution to both the target and other would-be aggressors','The Hoare-Laval affair demonstrates that coalition unity in sanctions requires genuine alignment of political will — if leading members privately prefer appeasement, the sanctions regime becomes a performative exercise rather than a coercive instrument','Non-participation by major non-member states (US, Germany) in the 1930s is the structural predecessor of China and Russia''s non-participation in modern sanctions regimes — collective security requires near-universal participation to be effective against a major oil-importing power'],
  ARRAY['League-of-Nations','Italy','Abyssinia','Ethiopia','collective-security','historical','failure','1930s'],
  ARRAY['https://en.wikipedia.org/wiki/Abyssinia_Crisis','League of Nations Official Journal 1935-1936','Hoare-Laval Pact documents'],
  'https://en.wikipedia.org/wiki/Abyssinia_Crisis',
  'The League of Nations sanctions against Italy (1935-1936) are the foundational failure case in sanctions history. Despite 50-state participation, sanctions deliberately excluded oil — Italy''s most critical military import — because of Anglo-French political timidity. The Hoare-Laval Pact revealed secret appeasement plans, exposing coalition bad faith. The failure destroyed the League''s credibility and emboldened Hitler and Mussolini toward WWII. Direct structural parallel to modern cases where key commodities (Russian energy, Iranian oil) are excluded from sanctions packages due to coalition economic interests.'
),

-- 18. Japan Oil Embargo 1941
(
  'JPN1941_OIL',
  'US Oil Embargo Against Japan',
  '1941-07-26', '1941-12-07',
  ARRAY['US','UK','Netherlands'],
  'Japan', 3.00, 'energy',
  ARRAY['Compel Japan to withdraw from China and Indochina; halt Japanese imperial expansion; prevent Japan from threatening US Pacific interests and the Philippines'],
  true, false, 'critical',
  ARRAY['Freeze on all Japanese assets in the United States (July 26, 1941)','Total embargo on oil and gasoline exports to Japan (August 1, 1941)','British and Dutch East Indies oil embargo follows immediately','Iron and steel scrap embargo (September 1940, preceding)','Aviation gasoline export restrictions (July 1940, preceding)','Total trade suspension following asset freeze'],
  'Japan''s military occupation of French Indochina (July 1941); Japan''s ongoing war in China (since 1937) and the Nanjing Massacre; Japanese membership in Tripartite Pact with Germany and Italy',
  ARRAY['There were effectively no viable evasion methods — Japan had no alternative oil suppliers capable of meeting its needs; the Dutch East Indies and US together supplied 94% of Japan''s oil','Japan''s strategic response was military rather than evasion: planning for the seizure of Dutch East Indies oil fields by force began immediately after the embargo','Japan attempted negotiations in Washington (Hull-Nomura talks) seeking sanctions relief in exchange for partial withdrawal from China — but no agreement was reached before the military timetable forced action'],
  '{"gdp_change_pct": null, "oil_export_change_pct": -94, "inflation_pct": null, "currency_devaluation_pct": null, "alternative_partners": []}',
  'backfire', 'no',
  '{"scenarios": [{"label": "compliance", "probability": 0.20}, {"label": "military_escalation", "probability": 0.60}, {"label": "negotiation", "probability": 0.20}], "gdp_impact_pct": -5}',
  '{"scenarios": [{"label": "compliance", "probability": 0.05}, {"label": "military_escalation", "probability": 0.85}, {"label": "negotiation", "probability": 0.10}], "gdp_impact_pct": null}',
  0.03, 1, NULL,
  ARRAY['July 26, 1941: Asset freeze — initially intended by some US officials as only a partial oil restriction, but mid-level Treasury and State Department officials implemented it as a total embargo, cutting Japan off from 94% of its oil overnight','August-November 1941: Hull-Nomura negotiations fail; Japan''s Imperial conference approves southern advance plan contingent on diplomatic failure; military timetable countdown begins','December 7, 1941: Japan attacks Pearl Harbor simultaneously with invasions of Philippines, Malaya, and Dutch East Indies — the most dramatic case in history of sanctions provoking military conflict'],
  'Japan attacked Pearl Harbor December 7, 1941, bringing the US into World War II. Japan occupied Dutch East Indies oil fields (Borneo, Sumatra) and sustained its war effort on captured oil for four years until US naval blockade and strategic bombing destroyed Japan''s oil import capacity by 1944-45.',
  ARRAY['Total oil embargo against a heavily oil-dependent military power with no alternative suppliers and expansionist military capacity can provoke military conflict rather than political compliance — the Japan case is the definitive historical example of sanctions as a casus belli','Implementation details matter critically: US officials intended a partial restriction that was implemented as a total cut-off by subordinate officials; the gap between policy intent and implementation had world-historical consequences','When the sanctioned state calculates that military force can seize the sanctioned resource (oil fields) at lower cost than sustained sanctions compliance, military action becomes rational — a calculation that only applies when the target has strong military capacity and geographic proximity to the resource'],
  ARRAY['Japan','oil-embargo','Pearl-Harbor','WWII','historical','backfire','escalation'],
  ARRAY['https://en.wikipedia.org/wiki/Prelude_to_the_attack_on_Pearl_Harbor','Hull-Nomura talks 1941','US National Archives WWII oil embargo documents'],
  'https://en.wikipedia.org/wiki/Prelude_to_the_attack_on_Pearl_Harbor',
  'The US oil embargo against Japan (1941) is the definitive backfire case — the only historical instance of sanctions directly provoking a military attack on the sanctioning state. Japan received 94% of its oil from the US and Dutch East Indies; with no alternative suppliers and expansionist military capacity, it calculated that seizing oil fields by force was less costly than compliance. Pearl Harbor followed 4 months after the embargo. Key lesson: total embargoes against military powers with no evasion route and access to target resources by force are existentially escalatory.'
),

-- 19. Pakistan Nuclear 1998
(
  'PAK1998_NUCLEAR',
  'Pakistan Nuclear Test Sanctions (Glenn Amendment)',
  '1998-05-28', '2001-09-22',
  ARRAY['US','Japan','Canada','EU (partial)'],
  'Pakistan', 0.15, 'finance_technology',
  ARRAY['Punish nuclear proliferation; deter further nuclear development; pressure Pakistan to sign the Comprehensive Nuclear-Test-Ban Treaty (CTBT) and Nuclear Non-Proliferation Treaty (NPT)'],
  true, false, 'medium',
  ARRAY['Glenn Amendment automatic sanctions: termination of US development assistance','Prohibition on US government military sales and financing','Opposition to loans from international financial institutions (IMF, World Bank)','Prohibition on US bank loans and credit to Pakistan','Restrictions on exports of specific goods and technology (dual-use)','Suspension of US Overseas Private Investment Corporation (OPIC) activities'],
  'Pakistan conducted five nuclear tests on May 28 and one on May 30, 1998 (Chagai-I and Chagai-II), in response to India''s tests of May 11-13, 1998',
  ARRAY['Saudi Arabia provided emergency financial assistance and deferred oil payment terms to cushion Pakistan against immediate balance-of-payments crisis','China — Pakistan''s all-weather ally and itself a nuclear power — provided diplomatic cover, continued military cooperation, and economic assistance outside the US sanctions framework','Clinton administration quickly weakened the sanctions through presidential waivers and exemptions; Congress exempted food exports within months','IMF program negotiations continued despite US statutory sanctions, with US ultimately supporting a November 1998 IMF package rather than allowing Pakistan to default'],
  '{"gdp_change_pct": -1.5, "oil_export_change_pct": null, "inflation_pct": 7.8, "currency_devaluation_pct": 4.2, "alternative_partners": ["China","Saudi Arabia","UAE"]}',
  'negotiated_relief', 'no',
  '{"scenarios": [{"label": "compliance", "probability": 0.05}, {"label": "status_quo", "probability": 0.55}, {"label": "evasion", "probability": 0.30}, {"label": "sanctions_relief", "probability": 0.10}], "gdp_impact_pct": -1.5}',
  '{"scenarios": [{"label": "compliance", "probability": 0.03}, {"label": "status_quo", "probability": 0.40}, {"label": "evasion", "probability": 0.30}, {"label": "sanctions_relief", "probability": 0.27}], "gdp_impact_pct": -1.5}',
  0.08, 3, 40,
  ARRAY['October 1998: Clinton administration significantly weakens sanctions, offering relief packages to both India and Pakistan contingent on non-weaponization commitments — Senate waiver passes, beginning the unraveling of the sanctions regime','October 1999: General Musharraf seizes power in coup; IMF program suspended; Pakistan teeters on debt default — US faces difficult choice between punishing nuclear proliferator and stabilizing nuclear-armed failing state','September 22, 2001: Bush waives all remaining nuclear sanctions on Pakistan following September 11 attacks; Pakistan becomes frontline state in War on Terror — counterterrorism cooperation completely overrides nonproliferation sanctions'],
  'All nuclear-related sanctions waived by President Bush on September 22, 2001, in exchange for Pakistani cooperation in the Afghanistan war. Pakistan retained its nuclear weapons and never signed CTBT or NPT. The sanctions'' nonproliferation objective was entirely abandoned under strategic pressure.',
  ARRAY['Automatic statutory sanctions (Glenn Amendment) remove executive branch flexibility and create perverse outcomes: the US was forced to choose between punishing proliferation and maintaining a functional relationship with a nuclear-armed state in a strategic theater','Counterterrorism and counterproliferation objectives are frequently in direct conflict — September 11 demonstrated that the US would immediately subordinate nonproliferation sanctions to strategic military cooperation needs','Sanctions imposed simultaneously on both sides of a bilateral conflict (India and Pakistan both tested) create equal-treatment optics that undermine the coercive message — if both proliferators receive the same punishment regardless of strategic value, neither faces a meaningful deterrence signal'],
  ARRAY['Pakistan','nuclear','Glenn-Amendment','nonproliferation','9/11','South-Asia'],
  ARRAY['https://en.wikipedia.org/wiki/Nuclear_weapons_and_India%E2%80%93Pakistan_relations','Glenn Amendment text 22 USC 2799aa-1','US State Department Pakistan sanctions waivers 1998-2001'],
  'https://en.wikipedia.org/wiki/Nuclear_weapons_and_India%E2%80%93Pakistan_relations',
  'Pakistan nuclear test sanctions (1998-2001) illustrate the strategic competition trap: automatic Glenn Amendment sanctions were progressively waived as soon as they conflicted with counterterrorism cooperation needs after 9/11. Pakistan retained its nuclear weapons and never signed the CTBT or NPT. The key structural lesson is that automatic statutory sanctions remove executive flexibility and force binary choices between punishing proliferation and maintaining strategic relationships — a tension that US policymakers consistently resolve by abandoning nonproliferation objectives.'
),

-- 20. Haiti Junta 1991
(
  'HTI1991_JUNTA',
  'Haiti Military Junta Sanctions',
  '1991-10-08', '1994-09-19',
  ARRAY['US','OAS','UN'],
  'Haiti', 0.02, 'comprehensive',
  ARRAY['Restore President Aristide to power; re-establish democratic governance in Haiti'],
  true, true, 'critical',
  ARRAY['OAS trade embargo (October 1991) — all goods except medicine and food','Suspension of all foreign aid to Haitian government','UN arms embargo (Resolution 841, June 1993)','UN oil and petroleum products embargo (June 1993)','UN comprehensive trade ban (Resolution 917, May 1994) — all imports and exports excluding humanitarian goods','Asset freeze on Haitian military and government leaders','Prohibition on financial transactions with Haiti'],
  'Military coup on September 30, 1991, by Lieutenant General Raoul Cédras, overthrowing Haiti''s first democratically elected president Jean-Bertrand Aristide',
  ARRAY['Dominican Republic maintained a porous border through which goods (especially fuel) entered Haiti throughout the embargo period, with Dominican merchants profiting from the price differential','Military and police elites established control over fuel distribution during the oil embargo, ensuring sufficient supply for regime operations while civilian population suffered','Haitian military and FRAPH paramilitaries ran protection rackets on informal cross-border trade that the UN sanctions regime could not fully interdict without sealing the entire Dominican border','Governors Island Accord (July 1993) led to temporary sanctions suspension (August-October 1993) — junta reneged on implementation, then defied US military observers'],
  '{"gdp_change_pct": -30, "oil_export_change_pct": null, "inflation_pct": null, "currency_devaluation_pct": null, "alternative_partners": ["Dominican Republic"]}',
  'compliance', 'yes',
  '{"scenarios": [{"label": "compliance", "probability": 0.10}, {"label": "partial_compliance", "probability": 0.30}, {"label": "status_quo", "probability": 0.45}, {"label": "military_intervention", "probability": 0.15}], "gdp_impact_pct": -15}',
  '{"scenarios": [{"label": "compliance", "probability": 0.25}, {"label": "partial_compliance", "probability": 0.30}, {"label": "status_quo", "probability": 0.25}, {"label": "military_intervention", "probability": 0.20}], "gdp_impact_pct": -30}',
  0.70, 6, 36,
  ARRAY['July 1993: Governors Island Accord — Cédras agrees to Aristide''s return; sanctions suspended; UNMIH peacekeepers begin arriving, then turned back by armed civilians at port (October 1993)','May 1994: UN Resolution 917 imposes near-total trade embargo — the most comprehensive UN action to date in the Western Hemisphere; economic pain finally becomes severe enough to change military calculation','September 1994: US military intervention threat becomes credible — Carter-Nunn-Powell delegation negotiates Cédras''s peaceful departure hours before US airborne troops were airborne; Aristide returns October 15'],
  'Cédras and military leadership went into exile in Panama (September 1994) following US-brokered agreement under imminent threat of military invasion (Operation Uphold Democracy, authorized by UNSC Resolution 940). Aristide returned October 15, 1994. Sanctions lifted. The case demonstrates that sanctions plus credible military threat together achieved what sanctions alone could not.',
  ARRAY['Sanctions alone failed for three years in Haiti; it was the combination of comprehensive sanctions plus a credible, imminent threat of military force (Operation Uphold Democracy) that finally produced compliance — demonstrating the limits of sanctions as a standalone instrument','Humanitarian exceptions (food and medicine) in comprehensive embargoes do not prevent civilian suffering when the junta controls distribution channels — the Harvard study estimated 1,000 additional child deaths per month from the embargo''s collateral effects','Small states with heavy economic dependence on a single patron or neighboring country (Dominican Republic providing fuel lifeline) are systematically more resistant to sanctions than their apparent vulnerability suggests'],
  ARRAY['Haiti','democracy','coup','Aristide','OAS','UN','military-intervention','Caribbean'],
  ARRAY['https://en.wikipedia.org/wiki/Operation_Uphold_Democracy','UN Security Council Resolution 940 (1994)','Harvard School of Public Health Haiti embargo health study 1994'],
  'https://en.wikipedia.org/wiki/Operation_Uphold_Democracy',
  'Haiti military junta sanctions (1991-1994) are the clearest case where sanctions required a credible military threat to succeed. The OAS/UN sanctions failed for three years despite causing 30% GDP contraction; compliance came only when the Carter-Nunn-Powell mission arrived with 20,000 US troops airborne. The Dominican Republic border provided a persistent evasion route. The case is frequently cited to demonstrate that sanctions are most effective as force multipliers alongside credible military options, not as standalone coercive instruments.'
);
