import Link from 'next/link'

export const metadata = {
  title: 'Terms of Use — Sanctions Precedent',
}

export default function TermsPage() {
  return (
    <div className="max-w-2xl mx-auto px-8 py-16">

      <div className="mb-12">
        <Link
          href="/"
          className="text-[10px] uppercase tracking-[0.24em] transition-opacity hover:opacity-60 mb-8 inline-block"
          style={{ fontFamily: 'var(--font-mono)', color: 'var(--t3)' }}
        >
          ← Back
        </Link>
        <p
          className="text-[9.5px] uppercase tracking-[0.3em] mb-4"
          style={{ fontFamily: 'var(--font-mono)', color: 'var(--t3)' }}
        >
          Legal
        </p>
        <h1
          className="leading-tight tracking-tight"
          style={{ fontSize: 'clamp(2rem, 4vw, 3rem)', fontWeight: 700, color: 'var(--t1)' }}
        >
          Terms of Use
        </h1>
        <p
          className="mt-3 text-[12px]"
          style={{ fontFamily: 'var(--font-mono)', color: 'var(--t3)' }}
        >
          Last updated: March 2026 · Governed by the laws of Canada
        </p>
      </div>

      <div
        className="space-y-10 text-[14.5px] leading-[1.85]"
        style={{ color: 'var(--t2)' }}
      >

        <section>
          <h2
            className="mb-3 text-[11px] uppercase tracking-[0.24em]"
            style={{ fontFamily: 'var(--font-mono)', color: 'var(--t3)', marginBottom: '0.75rem' }}
          >
            1. Not Professional Advice
          </h2>
          <p>
            Sanctions Precedent is an analytical research tool. All outputs — including scenario
            forecasts, probability estimates, precedent summaries, and analytical memos — are
            generated from historical data and statistical models. They do not constitute legal
            advice, sanctions compliance advice, financial advice, investment advice, or policy
            recommendations of any kind.
          </p>
          <p className="mt-4">
            You should not rely on this platform as the sole basis for any legal, regulatory,
            financial, or strategic decision. If you require professional guidance, consult a
            qualified lawyer, sanctions compliance officer, or policy advisor.
          </p>
        </section>

        <section>
          <h2
            className="mb-3 text-[11px] uppercase tracking-[0.24em]"
            style={{ fontFamily: 'var(--font-mono)', color: 'var(--t3)' }}
          >
            2. No Guarantee of Accuracy
          </h2>
          <p>
            Outputs are derived from a curated database of historical sanctions episodes and
            probabilistic models trained on past outcomes. Historical patterns do not guarantee
            future results. Geopolitical situations are inherently complex and unpredictable.
          </p>
          <p className="mt-4">
            We make no representations or warranties — express or implied — regarding the
            completeness, accuracy, reliability, or fitness for any particular purpose of any
            output generated by this platform.
          </p>
        </section>

        <section>
          <h2
            className="mb-3 text-[11px] uppercase tracking-[0.24em]"
            style={{ fontFamily: 'var(--font-mono)', color: 'var(--t3)' }}
          >
            3. User Responsibility
          </h2>
          <p>
            By using this platform you accept sole responsibility for how you interpret and
            act on its outputs. Sanctions Precedent and its operators shall not be liable
            for any direct, indirect, incidental, or consequential damages arising from your
            use of, or reliance on, information produced by this service.
          </p>
        </section>

        <section>
          <h2
            className="mb-3 text-[11px] uppercase tracking-[0.24em]"
            style={{ fontFamily: 'var(--font-mono)', color: 'var(--t3)' }}
          >
            4. No Data Collection
          </h2>
          <p>
            This platform does not collect, store, or share personal information. Scenario
            queries are processed in real time and are not retained after your session ends.
            No cookies are used for tracking or advertising purposes.
          </p>
        </section>

        <section>
          <h2
            className="mb-3 text-[11px] uppercase tracking-[0.24em]"
            style={{ fontFamily: 'var(--font-mono)', color: 'var(--t3)' }}
          >
            5. Service Provided As-Is
          </h2>
          <p>
            This platform is provided on an "as-is" and "as-available" basis without warranty
            of any kind. We reserve the right to modify, suspend, or discontinue the service
            at any time without notice.
          </p>
        </section>

        <section>
          <h2
            className="mb-3 text-[11px] uppercase tracking-[0.24em]"
            style={{ fontFamily: 'var(--font-mono)', color: 'var(--t3)' }}
          >
            6. Governing Law
          </h2>
          <p>
            These terms are governed by and construed in accordance with the laws of Canada.
            Any disputes arising from your use of this platform shall be subject to the
            exclusive jurisdiction of the courts of Canada.
          </p>
        </section>

        <section>
          <h2
            className="mb-3 text-[11px] uppercase tracking-[0.24em]"
            style={{ fontFamily: 'var(--font-mono)', color: 'var(--t3)' }}
          >
            7. Changes to These Terms
          </h2>
          <p>
            We may update these terms from time to time. Continued use of the platform
            after any changes constitutes your acceptance of the revised terms. The date
            at the top of this page reflects the most recent update.
          </p>
        </section>

      </div>
    </div>
  )
}
